let mock = [{
  id:1,
  title:"By the Sword",
  director_last_name:"Skeete",
  company_name:"Sony Pictures",
  genre:"Drama",
  day_of_the_week:"Saturday",
  time:"7:00 PM"
},
{
  id:2,
  title:"Dollman",
  director_last_name:"MacEveley",
  company_name:"Paramount",
  genre:"Action|Comedy|Crime",
  day_of_the_week:"Tuesday",
  time:"10:30 PM"
},
{
  id:3,
  title:"Valentin (Valentín)",
  director_last_name:"Houseman",
  company_name:"Universal Pictures",
  genre:"Drama",
  day_of_the_week:"Thursday",
  time:"6:00 PM"
},
{
  id:4,
  title:"Nosferatu (Nosferatu, eine Symphonie des Grauens)",
  director_last_name:"Larvin",
  company_name:"Disney",
  genre:"Horror",
  day_of_the_week:"Saturday",
  time:"10:30 AM"
},
{
  id:5,
  title:"Toy",
  director_last_name:"Yeskov",
  company_name:"Sony Pictures",
  genre:"Comedy",
  day_of_the_week:"Saturday",
  time:"2:00 PM"
},
{
  id:6,
  title:"Nomad (Köshpendiler)",
  director_last_name:"Maffione",
  company_name:"Disney",
  genre:"Drama|War",
  day_of_the_week:"Tuesday",
  time:"10:30 PM"
},
{
  id:7,
  title:"Like Water",
  director_last_name:"Sheldrick",
  company_name:"Disney",
  genre:"Documentary",
  day_of_the_week:"Tuesday",
  time:"4:00 PM"},
{
  id:8,
  title:"My Science Project",
  director_last_name:"Hansberry","company_name":"Universal Pictures",
  genre:"Adventure|Sci-Fi",
  day_of_the_week:"Wednesday",
  time:"6:00 PM"},
{
  id:9,
  title:"Birdcage",
  director_last_name:"Farnin",
  company_name:"Sony Pictures",
  genre:"Comedy",
  day_of_the_week:"Saturday",
  time:"8:00 PM"},
{
  id:10,
  title:"Simon Magus",
  director_last_name:"Merrgan",
  company_name:"Warner Bros.",
  genre:"Drama|Fantasy| Mystery|Romance",
  day_of_the_week:"Sunday",
  time:"7:00 PM"},
{
  id:11,
  title:"Sister Street Fighter (Onna hissatsu ken)",
  director_last_name:"Atack",
  company_name:"Sony Pictures",
  genre:"Action|Drama",
  day_of_the_week:"Tuesday",
  time:"7:30 PM"},
{
  id:12,
  title:"Sherlock Holmes and the Masks of Death",
  director_last_name:"Whitesel",
  company_name:"Universal Pictures",
  genre:"Mystery",
  day_of_the_week:"Wednesday",
  time:"8:30 PM"},
{
  id:13,
  title:"Abendland",
  director_last_name:"Cracoe",
  company_name:"Universal Pictures",
  genre:"Documentary",
  day_of_the_week:"Saturday",
  time:"9:00 PM"},
{
  id:14,
  title:"Darkman II: Return of Durant",
  director_last_name:"Gregg",
  company_name:"Universal Pictures",
  genre:"Action|Crime|Horror",
  day_of_the_week:"Tuesday",
  time:"4:00 PM"},
{
  id:15,
  title:"Redemption: The Stan Tookie Williams Story",
  director_last_name:"Milmo",
  company_name:"Paramount",
  genre:"Crime|Documentary| Drama",
  day_of_the_week:"Wednesday",
  time:"8:30 PM"},
{
  id:16,
  title:"Corner Gas: The Movie",
  director_last_name:"Balham",
  company_name:"Universal Pictures",
  genre:"Comedy",
  day_of_the_week:"Sunday",
  time:"6:30 PM"},
{
  id:17,
  title:"The Swedish Moment",
  director_last_name:"Arthey",
  company_name:"Paramount",
  genre:"Comedy",
  day_of_the_week:"Friday",
  time:"8:00 PM"},
{
  id:18,
  title:"Lesson of the Evil (Aku no kyôten)",
  director_last_name:"Hains",
  company_name:"Paramount",
  genre:"Thriller",
  day_of_the_week:"Tuesday",
  time:"6:30 PM"
},
{
  id:19,"title":"Je m'appelle Elisabeth",
  director_last_name:"O'Kennedy",
  company_name:"Sony Pictures",
  genre:"(no genres listed)",
  day_of_the_week:"Wednesday",
  time:"3:00 PM"},
{
  id:20,
  title:"Ricky Rapper (Risto Räppääjä)",
  director_last_name:"Mc Curlye",
  company_name:"Paramount",
  genre:"Comedy|Musical",
  day_of_the_week:"Saturday",
  time:"3:30 PM"
},
{
  id:21,
  title:"Punchline",
  director_last_name:"Strank",
  company_name:"Disney",
  genre:"Comedy|Drama",
  day_of_the_week:"Saturday",
  time:"12:00 PM"
},
{
  id:22,
  title:"Attila (Attila the Hun)",
  director_last_name:"Sirl",
  company_name:"Pixar",
  genre:"Action|Adventure| Drama|War",
  day_of_the_week:"Tuesday",
  time:"5:30 PM"
},
{
  id:23,
  title:"Fireflies in the Garden",
  director_last_name:"Lewinton",
  company_name:"Warner Bros.",
  genre:"Drama",
  day_of_the_week:"Wednesday",
  time:"3:00 PM"
},
{
  id:24,
  title:"American Virgin",
  director_last_name:"Acors",
  company_name:"Universal Pictures",
  genre:"Comedy",
  day_of_the_week:"Friday",
  time:"10:00 PM"
},
{
  id:25,
  title:"Summer Days With Coo",
  director_last_name:"Maciaszek",
  company_name:"Paramount",
  genre:"Animation",
  day_of_the_week:"Thursday",
  time:"2:30 PM"
},
{
  id:26,
  title:"Shakespeare High",
  director_last_name:"Cater",
  company_name:"Pixar",
  genre:"Documentary",
  day_of_the_week:"Saturday",
  time:"2:30 PM"
},
{
  id:27,
  title:"Oscar and the Lady in Pink",
  director_last_name:"Thorneywork",
  company_name:"Paramount",
  genre:"Drama",
  day_of_the_week:"Tuesday",
  time:"10:30 PM"
},
{
  id:28,
  title:"Presenting Lily Mars",
  director_last_name:"Callard",
  company_name:"Sony Pictures",
  genre:"Comedy|Musical| Romance",
  day_of_the_week:"Tuesday",
  time:"6:30 PM"
},
{
  id:29,
  title:"Sekirei",
  director_last_name:"Razzell",
  company_name:"Paramount",
  genre:"(no genres listed)",
  day_of_the_week:"Tuesday",
  time:"10:30 AM"
},
{
  id:30,
  title:"Sting",
  director_last_name:"Hodgets",
  company_name:"Pixar",
  genre:"Comedy|Crime",
  day_of_the_week:"Thursday",
  time:"4:00 PM"},
{
  id:31,
  title:"Witness to Murder",
  director_last_name:"Wedge",
  company_name:"Paramount",
  genre:"Crime|Drama|Film-Noir|Thriller",
  day_of_the_week:"Saturday",
  time:"1:00 PM"},
{
  id:32,
  title:"Torch Song Trilogy",
  director_last_name:"Baildon",
  company_name:"Warner Bros.",
  genre:"Comedy|Drama|Romance",
  day_of_the_week:"Wednesday",
  time:"8:00 PM"},
{
  id:33,
  title:"Defenders of Riga",
  director_last_name:"Robart",
  company_name:"Sony Pictures",
  genre:"Action|Drama|War",
  day_of_the_week:"Saturday",
  time:"6:30 PM"},
{
  id:34,
  title:"Shrooms",
  director_last_name:"Lavarack",
  company_name:"Disney",
  genre:"Horror|Thriller",
  day_of_the_week:"Wednesday",
  time:"4:00 PM"},
{
  id:35,
  title:"Stand Up and Fight",
  director_last_name:"Wordesworth",
  company_name:"Pixar",
  genre:"Drama|Romance|Western",
  day_of_the_week:"Tuesday",
  time:"3:00 PM"},
{
  id:36,
  title:"Devil's Carnival",
  director_last_name:"Fulmen",
  company_name:"Warner Bros.",
  genre:"Horror|Musical",
  day_of_the_week:"Tuesday",
  time:"2:30 PM"},
{
  id:37,
  title:"War Lord",
  director_last_name:"Emberton",
  company_name:"Paramount",
  genre:"Drama|Romance|War",
  day_of_the_week:"Friday",
  time:"11:30 AM"},
{
  id:38,
  title:"Chhoti Si Baat",
  director_last_name:"Allsebrook",
  company_name:"Paramount",
  genre:"Comedy|Romance",
  day_of_the_week:"Sunday",
  time:"6:00 PM"},
{
  id:39,
  title:"Sharpe's Gold",
  director_last_name:"Robic",
  company_name:"Universal Pictures",
  genre:"Action|Adventure|War",
  day_of_the_week:"Monday",
  time:"7:00 PM"},
{
  id:40,
  title:"White Men Can't Jump",
  director_last_name:"Yerson",
  company_name:"Universal Pictures",
  genre:"Comedy|Drama",
  day_of_the_week:"Sunday",
  time:"1:30 PM"},
{
  id:41,
  title:"One Small Hitch",
  director_last_name:"Gouinlock",
  company_name:"Warner Bros.",
  genre:"Comedy|Romance",
  day_of_the_week:"Thursday",
  time:"10:30 PM"},
{
  id:42,
  title:"Nekromantik",
  director_last_name:"Winning",
  company_name:"Disney",
  genre:"Comedy|Horror",
  day_of_the_week:"Monday",
  time:"5:30 PM"},
{
  id:43,
  title:"Game of Chance (Onnenpeli)",
  director_last_name:"Di Ruggero",
  company_name:"Paramount",
  genre:"Comedy|Drama",
  day_of_the_week:"Saturday",
  time:"12:30 PM"},
{
  id:44,
  title:"Quintet",
  director_last_name:"Cremen",
  company_name:"Pixar",
  genre:"Mystery|Sci-Fi",
  day_of_the_week:"Wednesday",
  time:"10:00 PM"},
{
  id:45,
  title:"Kissed",
  director_last_name:"Chilver",
  company_name:"Disney",
  genre:"Drama|Romance",
  day_of_the_week:"Thursday",
  time:"10:00 AM"},
{
  id:46,
  title:"Shadows (Cienie)",
  director_last_name:"Ballintyne",
  company_name:"Pixar",
  genre:"Drama",
  day_of_the_week:"Wednesday",
  time:"3:00 PM"},
{
  id:47,
  title:"Dark Wind",
  director_last_name:"Leagas",
  company_name:"Disney",
  genre:"Action|Mystery",
  day_of_the_week:"Sunday",
  time:"9:00 PM"},
{
  id:48,
  title:"Boyz N the Hood",
  director_last_name:"Whitemarsh",
  company_name:"Sony Pictures",
  genre:"Crime|Drama",
  day_of_the_week:"Wednesday",
  time:"9:00 PM"},
{
  id:49,
  title:"Dracula",
  director_last_name:"Moloney",
  company_name:"Paramount",
  genre:"Horror",
  day_of_the_week:"Saturday",
  time:"4:30 PM"},
{
  id:50,
  title:"Pickpocket",
  director_last_name:"Calrow",
  company_name:"Paramount",
  genre:"Crime|Drama",
  day_of_the_week:"Thursday",
  time:"8:00 PM"
}]

export default mock;
